### ISSUE TITLE
Enable multiple gpus

### ISSUE THREAD

**Issue by Eleganze** [dfaker/df#30]
Tried to enable processing ok two gpus, but got an error about layers having the same name. Any easy way to get this working?

**Comment by dfaker** [comment]
This looks like an outstanding issue in keras: https://github.com/keras-team/keras/issues/8962 a few people seem to have patches in the works.

**Comment by MotorCityCobra** [comment]
I think I have a workaround. Two instances?

I open a terminal, start the environment, get to my df dir and I run...  

    $CUDA_VISIBLE_DEVICES=1 python train.py

Then, second instance. I literally repeat that exact same process EXACTLY while one is training. Same dir, same env, but instead of 1 I put 0

    $CUDA_VISIBLE_DEVICES=0 python train.py

(CUDA_VISIBLE_DEVICES=0 will only allow python to see your 0th GPU. I had to do a few restarts and attempts to get this to work without memory errors.)

Maybe dfaker can confirm but I believe the two training processes it starts running are both saving their own unique work to the saved model.  
The two instances seem to be playing nice with each other and building on each other's work. Though it is a little hard to tell. My only benchmark is from comparing face quality at x time vs what it was on one GPU.  
Weigh in here dfaker.

**Comment by dfaker** [comment]
No sadly you're imagining it, you're wasting gpu cycles half of the time.

**Comment by MotorCityCobra** [comment]
Darn. That would make mining rigs churn out some deepfakes.  

If I still have you, if I wanted to create aligned face images (with align_images_masked.py) bigger than 256, how would I do that? I looked at said script and it wasn't obvious how to make the images 512 or 1024.  
I know the model isn't geared to take them but I could possible use higher rez faces like this for something else.

**Comment by MotorCityCobra** [comment]
Is there anything left to run on the merged frames after merge_faces_larger.py?  

The faces I've swapped look pretty real, (except for eyes), but there is a literal mask effect around the face in most frames.  
It kinda just looks like the face was copied and pasted on from another image of a face with expression and lighting matching. Hard edges.

**Comment by dfaker** [comment]
In this project no, others like have done things like extra feathered alpha blending around the edges, various content aware merge schemes and histogram colour matching between source and generated face.
